### ISSUE TITLE
Long scan report lost after exception

### ISSUE THREAD

**Issue by rebolini-pablo** [maldevel/intelspy#5]
Hi, just to share the following error:

```[*] Finished scanning target <ip address> in 137 hours, 34 minutes, 35 seconds
[*] Task tcp/443/nikto on <ip address> finished successfully in 101 hours, 4 seconds
[*] Finished scanning target <ip address> in 101 hours, 39 seconds

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "intelspy.py", line 1328, in scan_host
    results = loop.run_until_complete(asyncio.gather(scan_services(loop, semaphore, target,
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "intelspy.py", line 998, in scan_services
    result = task.result()
  File "intelspy.py", line 437, in run_cmd
    results = await asyncio.gather(*output)
  File "intelspy.py", line 384, in read_stream
    imp = e('{target.address} - ' + p['description'] + '\n\n').strip()
KeyError: 'description'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "intelspy.py", line 1996, in <module>
    if future.result():
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'description'
```

The problem is since intelspy save the entire report at the end of all scans, if you reach this error (or another) you lost all your progress (in my case  ~100hs of scan), it would be great if intelspy save one report after each scan...

Thanks a lot

**Comment by maldevel** [comment]
The bug has been fixed in develop branch for next release. I will update the tool to store its results during the scans.
